[features]
resolution = true
skip-lint = false

[programs.devnet]
axiom_staking = "AX1oMst4k1ngYYYvLwNpDxPJWwVD8xZJwiHJWwK4z9pQ"

[programs.mainnet]
axiom_staking = "AX1oMst4k1ngYYYvLwNpDxPJWwVD8xZJwiHJWwK4z9pQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[workspace]
members = [
    "programs/axiom-staking"
]